FROM node:lts-alpine3.15 as build
WORKDIR /app
COPY . . 
RUN npm install
RUN npm run build

FROM keymetrics/pm2:latest-alpine
COPY package.json .
COPY ecosystem.config.js .
COPY --from=build /app/dist ./
RUN npm install --production
CMD ["pm2-runtime", "start", "ecosystem.config.js"]

